# Generated by Django 4.0.3 on 2022-03-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='profilelink',
            options={'verbose_name': 'Profile Link', 'verbose_name_plural': 'Profile Link'},
        ),
        migrations.AddField(
            model_name='profilelink',
            name='link',
            field=models.CharField(default='My link', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profilelink',
            name='link_name',
            field=models.CharField(default='Link Name', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profilelink',
            name='user',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='linkowner', to='base.profile'),
        ),
    ]
